spring:
  application:
    name: Graduating-Server
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_NAME:graduating}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 1234
secret:
  neis:
    apikey: ${NEIS_APIKEY}