spring:
  application:
    name: Graduating-Server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 1234
management:
  endpoints:
    web:
      base-path: /management
  endpoint:
    health:
      show-details: always
neis:
  apikey: ${NEIS_APIKEY}
public-data:
  kosaf-service-key: ${KOSAF_SERVICE_KEY}
jwt:
  expired:
    access: 3_600_000
    refresh: 300_000_000
  secret-key: ${JWT_SECRET}
oauth2:
  google:
    client-id:
      ios: ${GOOGLE_CLIENT_ID_IOS} # Put your google client id for ios 
      web: ${GOOGLE_CLIENT_ID_WEB} # Put your google client id for web
    client-secret: ${GOOGLE_CLIENT_SECRET} # Put your google client secret
    redirect-uri: ${GOOGLE_REDIRECT_URI} # Put your google redirect uri
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
    grant-type: authorization_code
  apple:
    bundle-id: ${APPLE_BUNDLE_ID} # ClientId, Put your apple bundle id
    key-id: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    audience: https://appleid.apple.com
    private-key: ${APPLE_P8_KEY}
    grant-type: authorization_code